---
title: "Lyrical Analysis"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(tidytext)
library(textclean)
library(stringdist)

lyric_cleaner <- function(lyrics){
  
  # Expand contractions
  lyrics <- replace_contraction(lyrics)
  
  # Remove unicode and ASCII junk
  lyrics <- iconv(lyrics, sub="", from="UTF-8", to="")
  lyrics <- gsub("<U+.*?>", "", lyrics)
  
  # Convert to lower case
  lyrics <- tolower(lyrics)
  
  # Remove handles
  lyrics <- gsub("@", " ", lyrics)
  
  # Remove hashtags
  lyrics <- gsub("#", " ", lyrics)
  
  # Remove hyperlinks
  url_pattern <- "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(s\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
  lyrics <- gsub(url_pattern, "", lyrics)
  
  # Replace ampersand with and
  lyrics <- str_replace_all(lyrics, "&amp", "and")
  
  # Remove punctuation, digits, and emojis
  lyrics <- gsub("'s ", " ", lyrics)
  lyrics <- gsub("[[:punct:]]", " ", lyrics)
  lyrics <- gsub("[[:digit:]]", "", lyrics)
  lyrics <- gsub(" ’", "", lyrics)
  lyrics <- gsub("s' ", "s ", lyrics)
  lyrics <- gsub("’ ", " ", lyrics)
  
  # Remove newline characters
  lyrics <- str_replace_all(lyrics, "[\r\n]" , " ")
  
  # Remove extra whitespace
  lyrics <- gsub("  ", " ", lyrics)
  lyrics <- gsub("  ", " ", lyrics)
  
  # Trim whitespace
  lyrics <- str_trim(lyrics, side="both")
  
  return(lyrics)
}
```

```{r}
artist <- readRDS("Data/RDS Files/artist.rds")
albums <- readRDS("Data/RDS Files/albums.rds")
tracks <- readRDS("Data/RDS Files/tracks.rds")
```

Getting lyrics merged
```{r}
files <- list.files(path="Data/SongLyrics", pattern='*.txt',
                    full.names=T, recursive = T)

lyrics <- lapply(lapply(files, read_file), lyric_cleaner)

df_lyrics <- data.frame(name = basename(files), 
                        text = unlist(lyrics)) %>% 
  left_join(data.frame(read.csv("Data/SongLyrics/FileIDCrosswalk.csv")) %>% 
              select(name, id))

tracks_wlyrics <- left_join(tracks, df_lyrics %>% select(-name))

saveRDS(tracks_wlyrics, "Data/RDS Files/tracks_wlyrics.rds")
```

Using AFINN rather than bing or nrc bc of this: https://paulvanderlaken.com/2017/12/27/sentiment-analysis-lexicon-quality/
```{r}
track_sentiment_afinn <- tracks_wlyrics %>% select(name, id, album_name, album_id, text) %>% 
  unnest_tokens("word", "text", token="words", format="text") %>% 
  inner_join(get_sentiments("afinn")) %>% 
  filter(word != "like") %>% # Filter out (literal) false positive from similes
  mutate(sentiment_dir = ifelse(value<0, "negative", "positive")) %>% 
  group_by(id, sentiment_dir) %>% 
  summarize(sum = sum(value), across()) %>% 
  select(-word, -value) %>% 
  distinct() %>% 
  pivot_wider(names_from = sentiment_dir, values_from = sum) %>% 
  replace_na(list(positive = 0, negative = 0)) %>% 
  ungroup() %>% 
  mutate(net = positive + negative) %>% 
  left_join(df_trackviz %>% select(id, order) %>% unique())

track_sentiment_afinn %>% 
  ggplot(aes(x=order, y=net, fill=factor(album_name))) +
  geom_bar(stat="identity") +
  scale_x_discrete(expand = c(0,0)) +
  scale_color_manual(values=colors) +
  scale_fill_manual(values=fills2) +
  theme_void() +
  theme(
    axis.text.y = element_text(size=7),
    axis.title.y = element_text(angle=90, size=9, 
                                margin=margin(0,5,0,0, unit="pt")),
    legend.position="none",
    strip.background = element_blank(),
    strip.text = element_text(angle=0, size=0, color="ivory",
                              margin=margin(1.19,0,0,0, unit="cm")),
    #strip.text = element_blank(),
    panel.spacing = unit(.05, "lines"),
    plot.margin = margin(0,.05,.05,0, unit="cm"),
    panel.background = element_rect(fill="ivory", color="ivory"),
    plot.background = element_rect(fill="ivory"),
    panel.grid.major = element_line(color="seashell3", 
                                    linewidth=.25, linetype="dotted"),
    text = element_text(family="Book Antiqua")
  ) +
  facet_wrap(~factor(album_name,
                     levels=unique(track_sentiment_afinn$album_name),), nrow=1,
             strip.position="bottom",
             scales="free_x",
             labeller=label_wrap_gen(15)) +
  annotations[[1]] +
  annotations[[2]] +
  annotations[[3]] +
  annotations[[4]] +
  annotations[[5]] +
  annotations[[6]] +
  annotations[[7]] +
  annotations[[8]] +
  annotations[[9]] +
  annotations[[10]] +
  annotations[[11]] +
  coord_cartesian(clip = 'off')


```

```{r}
library(syuzhet)
```


